# Generated by Django 6.0.6 on 2026-06-21 23:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0041_syn1_add_team_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='source',
            field=models.CharField(choices=[('email', 'email'), ('mcp', 'mcp'), ('api', 'api'), ('escalation', 'escalation'), ('web', 'web')], default='web', max_length=20),
        ),
        migrations.AddField(
            model_name='followupattachment',
            name='quarantine_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followupattachment',
            name='s3_key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='followupattachment',
            name='scan_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followupattachment',
            name='scan_status',
            field=models.CharField(choices=[('pending', 'pending'), ('clean', 'clean'), ('quarantined', 'quarantined'), ('scan_error', 'scan_error')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='followupattachment',
            name='size_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='email_message_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='finding_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='linked_issue_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('email', 'email'), ('mcp', 'mcp'), ('api', 'api'), ('escalation', 'escalation'), ('web', 'web')], default='web', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketchange',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['team_id', 'status', '-created'], name='helpdesk_ti_team_id_72f15c_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['team_id', 'assigned_to', 'status'], name='helpdesk_ti_team_id_deb11d_idx'),
        ),
        migrations.AddConstraint(
            model_name='followup',
            constraint=models.UniqueConstraint(condition=models.Q(('message_id__isnull', False)), fields=('team_id', 'message_id'), name='helpdesk_followup_team_msgid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('email_message_id__isnull', False)), fields=('team_id', 'email_message_id'), name='helpdesk_ticket_team_email_msgid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('team_id', 'idempotency_key'), name='helpdesk_ticket_team_idempotency_uniq'),
        ),
    ]
