# Generated by Django 6.0.6 on 2026-06-22 01:42

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0043_syn3_enable_rls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'base_manager_name': 'upstream_objects', 'verbose_name': 'Checklist', 'verbose_name_plural': 'Checklists'},
        ),
        migrations.AlterModelOptions(
            name='checklisttask',
            options={'base_manager_name': 'upstream_objects', 'ordering': ('position',), 'verbose_name': 'Checklist Task', 'verbose_name_plural': 'Checklist Tasks'},
        ),
        migrations.AlterModelOptions(
            name='followup',
            options={'base_manager_name': 'upstream_objects', 'ordering': ('date',), 'verbose_name': 'Follow-up', 'verbose_name_plural': 'Follow-ups'},
        ),
        migrations.AlterModelOptions(
            name='followupattachment',
            options={'base_manager_name': 'upstream_objects', 'ordering': ('filename',), 'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'base_manager_name': 'upstream_objects', 'get_latest_by': 'created', 'ordering': ('id',), 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketcc',
            options={'base_manager_name': 'upstream_objects'},
        ),
        migrations.AlterModelOptions(
            name='ticketchange',
            options={'base_manager_name': 'upstream_objects', 'verbose_name': 'Ticket change', 'verbose_name_plural': 'Ticket changes'},
        ),
        migrations.AlterModelOptions(
            name='ticketcustomfieldvalue',
            options={'base_manager_name': 'upstream_objects', 'verbose_name': 'Ticket custom field value', 'verbose_name_plural': 'Ticket custom field values'},
        ),
        migrations.AlterModelOptions(
            name='ticketdependency',
            options={'base_manager_name': 'upstream_objects', 'verbose_name': 'Ticket dependency', 'verbose_name_plural': 'Ticket dependencies'},
        ),
        migrations.AlterModelManagers(
            name='checklist',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('upstream_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='checklisttask',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('upstream_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='followup',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('upstream_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='followupattachment',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('upstream_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='ticket',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('upstream_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='ticketcc',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('upstream_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='ticketchange',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('upstream_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='ticketcustomfieldvalue',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('upstream_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='ticketdependency',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('upstream_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
