# Generated by Django 6.0.6 on 2026-07-01 07:31

import helpdesk.models
import helpdesk.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0045_syn5_add_ticket_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupattachment',
            name='file',
            field=models.FileField(db_index=True, max_length=1000, upload_to=helpdesk.models.attachment_path, validators=[helpdesk.validators.validate_file_extension], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='kbiattachment',
            name='file',
            field=models.FileField(db_index=True, max_length=1000, upload_to=helpdesk.models.attachment_path, validators=[helpdesk.validators.validate_file_extension], verbose_name='File'),
        ),
    ]
